### PR TITLE
Update form styles

### LINKED ISSUE #217: Form legend styles need revisiting
`<legend>` right now receives a larger font size. There are instances within the form where the legend looks larger than other form labels which appears odd (see checkbox legend and the legend that appear before the radio buttons.
image
image

### PR DESCRIPTION
**Pull request by skoolbus39**
Fixes #217

### CODE REVIEW

**Comment by ericras** [comment]
Looks good to me.  My only question: are there any breaking changes in this? For example, I see some stuff is carried over and marked "TODO: deprecate" like .dcf-input-text but what about .dcf-input-group-form ? That just appears to be removed.

**Comment by skoolbus39** [comment]
`.dcf-form-controls-inline` does what `.dcf-input-group-form` did. It was renamed because it can be used for more than just input groups. I added it back (to avoid breaking) and, like the others, marked it for deprecation. Good catch.

**Comment by Shaderpixel** [comment]
1. When using `.dcf-form-controls-inline`, there is no margin between label and input control
2. When using `.dcf-form-controls-inline` with controls that has `width: 100%;`, input becomes stacked instead of staying inline on wider viewports. Try adding `flex: 1 1 40em;` to the input & select. Change flex-basis as desired to fine tune when to inline control should become stacked.

**Comment by skoolbus39** [comment]
@Shaderpixel and I have talked in person about the inline form controls and have landed on a solution that we feel should cover most use cases—stack `.dcf-form-controls-inline` by default and display inline as space allows starting at the small breakpoint. This should reduce the likelihood of a mix of some inline controls displaying stacked and others displaying inline.

**Pull request merged**
