### PR TITLE
Proposed fix for responsive table mobile display

### PR DESCRIPTION
**Pull request by beckyaiken**
- Changed `display: grid` on`<td>` so links, spans, etc. inside wrap as expected
- Made `<th>` inside `<tbody>` `display: block;` so they go the full width of the table
- Made `data-label` only apply to cells that have that attribute

### CODE REVIEW

**Review by skoolbus39 — APPROVED** [review]

**Comment by skoolbus39** [comment]
Thanks for the pull request, @beckyaiken! Merged!

**Comment by beckyaiken** [comment]
Screen Shot 2020-12-04 at 9 48 56 AM

I still see the issue caused by display:grid (see https://unlcms.unl.edu/raiken2-test-site/responsive-table-test). Did this update get added to the CMS?

**Comment by skoolbus39** [comment]
@beckyaiken This was merged, but you're also not wrong – it is indeed still displaying as `grid` in production. I'm investigating.

**Comment by skoolbus39** [comment]
@beckyaiken Found it! It got merged into the `master` branch but not the `2.0` branch. We're moving away from using terms like `master` and instead focusing on version numbers. `2.0` is now the main branch. I will get your changes into that branch and then pull them into our WDN templates before next week's release. Thanks for following up on this.

**Comment by beckyaiken** [comment]
Great! Thanks Ryan.

**Pull request merged**
